Pr/csr initials
ripe-tech/ripe-sdk pull request #207
Opened 2020-10-23 15:07 UTC by veryprofessionaldodo

| - | - |
| --- | --- |
| Dependencies | [ThreeJS](https://github.com/mrdoob/three.js), [POSTPROCESS](https://github.com/vanruesc/postprocessing)
| Decisions | There are several limitations to the Pre-Render Compose strategy, so a Client-Side Rendering strategy was implemented. Using the ThreeJS graphics engine, this branch integrates real-time rendering with the Ripe SDK as an alternative to the classic pre-render approach. Currently, there is support for changing parts using setParts, orbital rotation around the mesh, crossfades, several easing strategies for rotations and highlights, rotation locking to horizontal or vertical axis, initials support, some postprocessing features such as bloom, multi-animation support in a glTF file, mouse drift and more. |
| Animated GIF | ![full3](https://user-images.githubusercontent.com/22790704/97020676-bfd2ef00-1549-11eb-9dc7-0cd8ca6b629c.gif) |

2020-11-10 09:22 UTC, joamag requested changes

2020-11-10 09:22 UTC, joamag commented on src/python/ripe_demo/static/js/main.js
> +                    //introAnimation: "mesh_slide_in_1.fbx",
no commented code

2020-11-10 09:29 UTC, veryprofessionaldodo commented on src/python/ripe_demo/static/js/main.js
> +                    //introAnimation: "mesh_slide_in_1.fbx",
Fixed!

2020-11-11 15:41 UTC, joamag commented
@veryprofessionaldodo don't forget to run `npm run pretty` before any commit

2020-11-11 15:54 UTC, joamag commented
@veryprofessionaldodo Other notes:
* `var` is not allowed, please use `const` or `let`
* Avoid committing code that is commented out
* Document the expected data types for parameters and return values - avoid `{*}` in docstrings
* Start inline comments with lowercase letters

2020-11-11 16:03 UTC, joamag commented
@veryprofessionaldodo more notes
* Use `for of` for simple iterator driven iteration instead of using index based iteration
```javascript
    for (let i = 0; i < this.raycastingMeshes.length; i++) {
        await this.assetManager.disposeMesh(this.raycastingMeshes[i]);
    }
```

becomes

```javascript
    for (const raycastingMesh of this.raycastingMeshes) {
        await this.assetManager.disposeMesh(raycastingMesh);
    }
```

2020-11-11 16:08 UTC, joamag commented
@veryprofessionaldodo more notes
* Use always `"` instead of `'`
* Do not commit `TODO`, if not implemented prefer the `NotImplementedException`

2020-11-11 17:43 UTC, joamag commented
@veryprofessionaldodo one more
* Avoid adding large blobs to the repo as that increases the overall repo size

2020-12-14 12:40 UTC, joamag commented
@veryprofessionaldodo this branch is now locked if you need to do some quick fixes regarding visual issues please fork this branch

2021-02-12 19:21 UTC, joamag commented
Closing this PR for now will re-open once the branch is more stable

2022-02-04 09:08 UTC, veryprofessionaldodo commented
@joamag Just saw that I got assigned to this, but this is branch is more than half a year out of date compared to the [sandbox version](https://github.com/ripe-tech/sandbox/tree/pr/ripe-csr). I think that this should be closed, and a new, more fleshed out, more correct version should be made from that version.

2022-02-11 15:38 UTC, veryprofessionaldodo commented
@joamag Should this PR be closed? It's quite out of date as I wrote before, with the new [sandbox version](https://github.com/ripe-tech/sandbox/tree/pr/ripe-csr) having almost a year more of updates. What do you think?

2022-02-12 11:07 UTC, joamag commented
> @joamag Should this PR be closed? It's quite out of date as I wrote before, with the new [sandbox version](https://github.com/ripe-tech/sandbox/tree/pr/ripe-csr) having almost a year more of updates. What do you think?

We'll probably have to start with this API and then refactor and add new features that have been developed on top of this.

2022-02-14 09:26 UTC, veryprofessionaldodo commented
@joamag I strongly suggest against using this PR for completing CSR, for a lot of different reasons. The repo I [mentioned before](https://github.com/ripe-tech/sandbox/tree/pr/ripe-csr) has these changes (and more that I can't remember):
- is already completely self-contained, and serves only as an optional extension of the SDK, just like requested, with a [PR](https://github.com/ripe-tech/ripe-sdk/pull/318) done to support this;
- features the capability to generate masked images for RIPE-Compose (a lot of changes were done for this);
- much higher resilience for random errors;
- capability to highlight multiple meshes using the same hover;
- complete compliance with latest version of CSR specification, which means it will work using the latest updates done to the editor. This includes all the capabilities allowed by the latest specification, including part grouping and smart defaults for meshes not in the build;
- improved compatibility with current events from RIPE SDK, including config;
- major refactors to streamline texture loading;
- improvements to how views are handled;
- major improvements to asynchronous processing of events for better performance and time-to-first-frame;

And all of this is done while the code simultaneously underwent major refactors for improved code structure, and a huge number of bug fixes. If I had to guess, between 50 and 80 bugs were solved in the new version. 

I suggest using the other branch for CSR. We currently have under 7 weeks until the end of Q1, and there's still more work to be done outside of CSR to get this in a production-ready state. I don't think we have the time to backport all the features and fixes to this outdated branch, while still working on the other requirements to get this running in time.

2022-09-12 15:56 UTC, closed without merging