#39: Added currency to structure
ripe-tech/ripe-sdk pull request #221
Opened 2020-11-26 15:17 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Derived from https://github.com/ripe-tech/ripe-sdk-components-vue/pull/43#issuecomment-734344558 |
| Dependencies | -- |
| Decisions | Added currency to `structure`. <br> >Switched `isEmpty` to keys.length > 0, because it was causing error.  |
| Animated GIF | -- |

2020-11-26 17:40 UTC, gcandal commented
@BeeMargarida this is probably not the way to go since we're messing with the meaning of `structure`, which should only represent a customization+personalization and not the full set of SDK settings.

What I was thinking was changing `setStructure` so that it would receive an extra `options` argument as well, similarly to what already happens with `fromStructure`.

Regarding the `isEmpty` part, can you detail what was the problem?

2020-11-26 17:45 UTC, BeeMargarida commented
> @BeeMargarida this is probably not the way to go since we're messing with the meaning of `structure`, which should only represent a customization+personalization and not the full set of SDK settings.
> 
> What I was thinking was changing `setStructure` so that it would receive an extra `options` argument as well, similarly to what already happens with `fromStructure`.
> 
> Regarding the `isEmpty` part, can you detail what was the problem?

Oh, got it, I misunderstood. Will correct!
Regarding the isEmpty, it was throwing the error that it was not a function. I don't think we are using lodash, and didn't see any other uses, in other places it is using the `Object.keys(..).length > 0`.

2020-11-26 17:48 UTC, gcandal commented
You're right, `isEmpty` is for strings. Can you open that as a separate PR? It's probably an insta-merge.

2020-11-26 18:14 UTC, gcandal requested changes

2020-11-26 18:14 UTC, gcandal commented on src/js/base/ripe.js
> +    await instance.setStructure(structure, safe, options);
I don't think you need this here, given that in the line above you're already passing the options

2020-11-27 10:01 UTC, gcandal commented
Let's do this differently

2020-11-27 10:01 UTC, closed without merging