#260 Refresh shipping methods
ripe-tech/ripe-sdk pull request #328
Opened 2021-11-08 11:38 UTC by NFSS10

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/260|
| Dependencies | TODO |
| Decisions | Add `refreshShippingOrder` and `refreshShippingOrderP` |

2021-11-08 12:59 UTC, joao-conde requested changes

2021-11-08 12:59 UTC, joao-conde commented on src/js/api/order.js
> +
Add documentation similar to https://github.com/ripe-tech/ripe-sdk/blob/ns/260-bus_refresh_shipping/src/js/api/order.js#L241

2021-11-08 13:09 UTC, joao-conde approved these changes

2021-11-12 15:42 UTC, joamag approved these changes

2021-11-12 15:43 UTC, merged