#281 Bulking support
ripe-tech/ripe-sdk pull request #343
Opened 2022-01-11 10:06 UTC by joaofsl

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281|
| Decisions | Add missing methods to create a bulk order.|

2022-01-11 10:19 UTC, BeeMargarida commented
@joaofsl Missing changelog, also this needs to be ported to ripe-api in Python

2022-01-11 10:25 UTC, BeeMargarida commented
@joaofsl Please link the issue in the changelog entry

2022-01-11 10:27 UTC, BeeMargarida commented on src/js/api/bulk-order.js
> +ripe.Ripe.prototype.importBulkOrder = function(name, brand, orders, options, callback) {
the name brand and orders could not be inside the options, like `importOrder`?

2022-01-11 10:43 UTC, BeeMargarida requested changes
Small thing

2022-01-11 10:43 UTC, BeeMargarida commented on src/js/api/bulk-order.js
> + * @returns {XMLHttpRequest} Resulting information for the callback execution.
```suggestion
 *  @returns {Promise} The bulk order's data.

```

2022-01-11 10:43 UTC, BeeMargarida commented on src/js/api/bulk-order.js
> + * @param {Function} callback Function with the result of the request.
does not receive callback

2022-01-11 10:43 UTC, BeeMargarida commented on src/js/api/bulk-order.js
> + * @param {Object} orders The list of the order ids for the bulk order.
```suggestion
 * @param {Object} orders The list of the order IDs for the bulk order.

```

2022-01-11 17:44 UTC, BeeMargarida approved these changes

2022-02-21 18:58 UTC, hugo-gomes reviewed
@joaofsl any update on this?

2022-02-23 12:00 UTC, joaofsl commented on src/js/api/bulk-order.js
> + * @see {link https://docs.platforme.com/#order-endpoints-import}
Yes, we don't have any documentation regarding the bulk orders

2022-02-23 13:52 UTC, BeeMargarida commented on src/js/api/bulk-order.js
> + * @see {link https://docs.platforme.com/#order-endpoints-import}
@hugo-gomes A release is needed in the docs, the bulk order documentation is already done but not yet deployed

2022-02-23 15:28 UTC, hugo-gomes commented on src/js/api/bulk-order.js
> + * @see {link https://docs.platforme.com/#order-endpoints-import}
@ripe-tech/tech-devops can we "release the kraken" in the near future? :)

2022-02-24 09:54 UTC, joamag approved these changes

2022-02-24 09:54 UTC, merged