#4703 Add size to rules
ripe-tech/ripe-sdk pull request #373
Opened 2022-03-15 16:54 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4703 |
| Dependencies | https://github.com/ripe-tech/ripe-core/pull/4707 |
| Decisions | - Adapt ripe-sdk methods to new size dimensions in rules. |

2022-03-15 19:52 UTC, BeeMargarida requested changes
Shouldn't this be done for `transport-rule` and `availability-rule` as well?

2022-03-16 10:42 UTC, 3rdvision commented
> Shouldn't this be done for `transport-rule`, `availability-rule` and `price-rule` as well?

for which methods? Everything is passed through options and as for the resolve method, there's only `resolveInvoiceRule`

2022-03-16 10:56 UTC, BeeMargarida commented
> > Shouldn't this be done for `transport-rule`, `availability-rule` and `price-rule` as well?
> 
> for which methods? Everything is passed through options and as for the resolve method, there's only `resolveInvoiceRule`

Nvm, i did not notice those don't have resolve methods. However, `transport-rule` should have (I guess it wasn't ported at the time) because there is an endpoint for it - https://github.com/ripe-tech/ripe-core/blob/7a0a2eed80467916980ecd02f487d307ca5cfa60/src/ripe_core/controllers/api/rules/transport_rule.py#L49
Perhaps this PR should add it, since it is basically the same as the one for invoice rule

2022-03-16 11:46 UTC, BeeMargarida commented on src/js/api/transport-rule.js
> + * Gets an existing transport rule filtered by brand, model and country.
```suggestion
 * Gets an existing transport rule filtered by brand, model, country, factory and size.

```

2022-03-16 11:55 UTC, BeeMargarida approved these changes

2022-03-16 12:07 UTC, joao-conde approved these changes

2022-03-16 12:28 UTC, 3rdvision commented
blocked until https://github.com/ripe-tech/ripe-core/pull/4707 is merged

2022-03-16 15:53 UTC, joamag approved these changes

2022-03-16 15:53 UTC, merged