YSL: Passing compose `options` option
ripe-tech/ripe-sdk pull request #386
Opened 2022-04-07 14:24 UTC by 3rdvision

| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-sdk/pull/378 (to avoid conflicts) |
| Decisions | - Add missing option for composition `options` to be passed in the URL. |

2022-04-13 09:56 UTC, BeeMargarida commented
missing adding options to method `updateOptions` in image

2022-04-13 14:57 UTC, BeeMargarida approved these changes

2022-04-13 15:13 UTC, joao-conde approved these changes

2022-04-14 08:55 UTC, joamag requested changes

2022-04-14 08:55 UTC, joamag commented on src/js/visual/image.js
> +    this.extraOptions = this.options.options || null;
maybe use `this._options` instead?

2022-04-14 10:49 UTC, joamag requested changes

2022-04-14 10:49 UTC, joamag commented on src/js/visual/image.js
> +    this._options = this.options.options || null;
on second thought maybe use `composeOptions` following the naming of `composeLogic` what do you think?

2022-04-15 10:14 UTC, merged