fix: no mask buffers if useMasks false
ripe-tech/ripe-sdk pull request #445
Opened 2022-11-22 12:03 UTC by joao-conde

| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | If masks are turned off, we cant create the mask buffers (image elements) because they will load the masks anyways even if disabled. |
| Animated GIF | -- |

2022-11-22 12:55 UTC, 3rdvision requested changes

2022-11-22 12:55 UTC, 3rdvision commented on src/js/visual/configurator-prc.js
> +    if (this.useMasks) {
I'd say that this should also be passing if `this.useMasks` is null or even undefined

```suggestion
    if (this.useMasks !== false) {

```

2022-11-22 12:55 UTC, 3rdvision commented on src/js/visual/configurator-prc.js
> +    if (this.useMasks) {
same for other `if (this.useMasks)`

2022-11-23 09:59 UTC, joao-conde commented
Closing this as the solution is not ideal

2022-11-23 09:59 UTC, closed without merging